/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Type__2 = IDL.Variant({
  'other' : IDL.Null,
  'equipment' : IDL.Null,
  'building' : IDL.Null,
  'vehicle' : IDL.Null,
});
export const Condition = IDL.Variant({
  'good' : IDL.Null,
  'heavyDamage' : IDL.Null,
  'lightDamage' : IDL.Null,
});
export const FasilitasData = IDL.Record({
  'id' : IDL.Text,
  'acquisitionYear' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'location' : IDL.Text,
  'fasilitasType' : Type__2,
  'condition' : Condition,
});
export const Status__2 = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
});
export const Type__1 = IDL.Variant({
  'social' : IDL.Null,
  'cleaning' : IDL.Null,
  'security' : IDL.Null,
  'monthly' : IDL.Null,
});
export const IuranData = IDL.Record({
  'id' : IDL.Text,
  'wargaId' : IDL.Text,
  'status' : Status__2,
  'month' : IDL.Nat,
  'total' : IDL.Nat,
  'createdAt' : Time,
  'year' : IDL.Nat,
  'wargaName' : IDL.Text,
  'iuranType' : Type__1,
  'paymentDate' : IDL.Opt(IDL.Text),
});
export const KKData = IDL.Record({
  'id' : IDL.Text,
  'members' : IDL.Vec(IDL.Text),
  'head' : IDL.Text,
  'createdAt' : Time,
  'address' : IDL.Text,
  'number' : IDL.Text,
});
export const Status__1 = IDL.Variant({
  'active' : IDL.Null,
  'archived' : IDL.Null,
});
export const Category = IDL.Variant({
  'emergency' : IDL.Null,
  'important' : IDL.Null,
  'general' : IDL.Null,
});
export const PengumumanData = IDL.Record({
  'id' : IDL.Text,
  'status' : Status__1,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : Time,
  'author' : IDL.Text,
  'category' : Category,
});
export const PengurusData = IDL.Record({
  'id' : IDL.Text,
  'period' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'phone' : IDL.Text,
  'photo' : IDL.Text,
  'position' : IDL.Text,
});
export const Status = IDL.Variant({
  'finished' : IDL.Null,
  'rejected' : IDL.Null,
  'processing' : IDL.Null,
  'waiting' : IDL.Null,
});
export const Type = IDL.Variant({
  'kk' : IDL.Null,
  'ktp' : IDL.Null,
  'other' : IDL.Null,
  'poor' : IDL.Null,
  'domicile' : IDL.Null,
});
export const SuratData = IDL.Record({
  'id' : IDL.Text,
  'wargaId' : IDL.Text,
  'status' : Status,
  'applicant' : IDL.Text,
  'completionDate' : IDL.Opt(IDL.Text),
  'suratType' : Type,
  'createdAt' : Time,
  'notes' : IDL.Opt(IDL.Text),
  'requestDate' : IDL.Text,
  'purpose' : IDL.Text,
});
export const StatusWarga = IDL.Variant({
  'kos' : IDL.Null,
  'tetap' : IDL.Null,
  'kontrak' : IDL.Null,
});
export const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
export const WargaData = IDL.Record({
  'id' : IDL.Text,
  'dob' : IDL.Text,
  'job' : IDL.Text,
  'nik' : IDL.Text,
  'status' : StatusWarga,
  'kkNumber' : IDL.Text,
  'createdAt' : Time,
  'fullName' : IDL.Text,
  'address' : IDL.Text,
  'gender' : Gender,
  'phone' : IDL.Text,
  'maritalStatus' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Statistics = IDL.Record({
  'totalActivePengumuman' : IDL.Nat,
  'totalKK' : IDL.Nat,
  'totalWaitingSurat' : IDL.Nat,
  'totalPaidIuranThisMonth' : IDL.Nat,
  'totalWarga' : IDL.Nat,
});
export const WebsiteSettings = IDL.Record({
  'mission' : IDL.Text,
  'name' : IDL.Text,
  'headPhone' : IDL.Text,
  'description' : IDL.Text,
  'history' : IDL.Text,
  'email' : IDL.Text,
  'fullAddress' : IDL.Text,
  'vision' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFasilitas' : IDL.Func([FasilitasData], [IDL.Text], []),
  'addIuran' : IDL.Func([IuranData], [IDL.Text], []),
  'addKK' : IDL.Func([KKData], [IDL.Text], []),
  'addPengumuman' : IDL.Func([PengumumanData], [IDL.Text], []),
  'addPengurus' : IDL.Func([PengurusData], [IDL.Text], []),
  'addSurat' : IDL.Func([SuratData], [IDL.Text], []),
  'addWarga' : IDL.Func([WargaData], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteFasilitas' : IDL.Func([IDL.Text], [], []),
  'deleteIuran' : IDL.Func([IDL.Text], [], []),
  'deleteKK' : IDL.Func([IDL.Text], [], []),
  'deletePengumuman' : IDL.Func([IDL.Text], [], []),
  'deletePengurus' : IDL.Func([IDL.Text], [], []),
  'deleteSurat' : IDL.Func([IDL.Text], [], []),
  'deleteWarga' : IDL.Func([IDL.Text], [], []),
  'filterIuranByMonthYear' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(IuranData)],
      ['query'],
    ),
  'filterIuranByStatus' : IDL.Func(
      [Status__2],
      [IDL.Vec(IuranData)],
      ['query'],
    ),
  'filterIuranByWarga' : IDL.Func([IDL.Text], [IDL.Vec(IuranData)], ['query']),
  'filterSuratByStatus' : IDL.Func([Status], [IDL.Vec(SuratData)], ['query']),
  'filterSuratByWarga' : IDL.Func([IDL.Text], [IDL.Vec(SuratData)], ['query']),
  'filterWargaByKK' : IDL.Func([IDL.Text], [IDL.Vec(WargaData)], ['query']),
  'filterWargaByStatus' : IDL.Func(
      [StatusWarga],
      [IDL.Vec(WargaData)],
      ['query'],
    ),
  'getAdminUsername' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFasilitas' : IDL.Func([IDL.Text], [IDL.Opt(FasilitasData)], ['query']),
  'getIuran' : IDL.Func([IDL.Text], [IDL.Opt(IuranData)], ['query']),
  'getKK' : IDL.Func([IDL.Text], [IDL.Opt(KKData)], ['query']),
  'getPengumuman' : IDL.Func([IDL.Text], [IDL.Opt(PengumumanData)], ['query']),
  'getPengurus' : IDL.Func([IDL.Text], [IDL.Opt(PengurusData)], ['query']),
  'getStatistics' : IDL.Func([], [Statistics], ['query']),
  'getSurat' : IDL.Func([IDL.Text], [IDL.Opt(SuratData)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWarga' : IDL.Func([IDL.Text], [IDL.Opt(WargaData)], ['query']),
  'getWebsiteSettings' : IDL.Func([], [IDL.Opt(WebsiteSettings)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActivePengumuman' : IDL.Func([], [IDL.Vec(PengumumanData)], ['query']),
  'listFasilitas' : IDL.Func([], [IDL.Vec(FasilitasData)], ['query']),
  'listIuran' : IDL.Func([], [IDL.Vec(IuranData)], ['query']),
  'listKK' : IDL.Func([], [IDL.Vec(KKData)], ['query']),
  'listPengumuman' : IDL.Func([], [IDL.Vec(PengumumanData)], ['query']),
  'listPengurus' : IDL.Func([], [IDL.Vec(PengurusData)], ['query']),
  'listSurat' : IDL.Func([], [IDL.Vec(SuratData)], ['query']),
  'listWarga' : IDL.Func([], [IDL.Vec(WargaData)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setWebsiteSettings' : IDL.Func([WebsiteSettings], [], []),
  'updateFasilitas' : IDL.Func([FasilitasData], [], []),
  'updateIuran' : IDL.Func([IuranData], [], []),
  'updateKK' : IDL.Func([KKData], [], []),
  'updatePengumuman' : IDL.Func([PengumumanData], [], []),
  'updatePengurus' : IDL.Func([PengurusData], [], []),
  'updateSurat' : IDL.Func([SuratData], [], []),
  'updateWarga' : IDL.Func([WargaData], [], []),
  'verifyAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Type__2 = IDL.Variant({
    'other' : IDL.Null,
    'equipment' : IDL.Null,
    'building' : IDL.Null,
    'vehicle' : IDL.Null,
  });
  const Condition = IDL.Variant({
    'good' : IDL.Null,
    'heavyDamage' : IDL.Null,
    'lightDamage' : IDL.Null,
  });
  const FasilitasData = IDL.Record({
    'id' : IDL.Text,
    'acquisitionYear' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'location' : IDL.Text,
    'fasilitasType' : Type__2,
    'condition' : Condition,
  });
  const Status__2 = IDL.Variant({ 'paid' : IDL.Null, 'unpaid' : IDL.Null });
  const Type__1 = IDL.Variant({
    'social' : IDL.Null,
    'cleaning' : IDL.Null,
    'security' : IDL.Null,
    'monthly' : IDL.Null,
  });
  const IuranData = IDL.Record({
    'id' : IDL.Text,
    'wargaId' : IDL.Text,
    'status' : Status__2,
    'month' : IDL.Nat,
    'total' : IDL.Nat,
    'createdAt' : Time,
    'year' : IDL.Nat,
    'wargaName' : IDL.Text,
    'iuranType' : Type__1,
    'paymentDate' : IDL.Opt(IDL.Text),
  });
  const KKData = IDL.Record({
    'id' : IDL.Text,
    'members' : IDL.Vec(IDL.Text),
    'head' : IDL.Text,
    'createdAt' : Time,
    'address' : IDL.Text,
    'number' : IDL.Text,
  });
  const Status__1 = IDL.Variant({ 'active' : IDL.Null, 'archived' : IDL.Null });
  const Category = IDL.Variant({
    'emergency' : IDL.Null,
    'important' : IDL.Null,
    'general' : IDL.Null,
  });
  const PengumumanData = IDL.Record({
    'id' : IDL.Text,
    'status' : Status__1,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : Time,
    'author' : IDL.Text,
    'category' : Category,
  });
  const PengurusData = IDL.Record({
    'id' : IDL.Text,
    'period' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'phone' : IDL.Text,
    'photo' : IDL.Text,
    'position' : IDL.Text,
  });
  const Status = IDL.Variant({
    'finished' : IDL.Null,
    'rejected' : IDL.Null,
    'processing' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const Type = IDL.Variant({
    'kk' : IDL.Null,
    'ktp' : IDL.Null,
    'other' : IDL.Null,
    'poor' : IDL.Null,
    'domicile' : IDL.Null,
  });
  const SuratData = IDL.Record({
    'id' : IDL.Text,
    'wargaId' : IDL.Text,
    'status' : Status,
    'applicant' : IDL.Text,
    'completionDate' : IDL.Opt(IDL.Text),
    'suratType' : Type,
    'createdAt' : Time,
    'notes' : IDL.Opt(IDL.Text),
    'requestDate' : IDL.Text,
    'purpose' : IDL.Text,
  });
  const StatusWarga = IDL.Variant({
    'kos' : IDL.Null,
    'tetap' : IDL.Null,
    'kontrak' : IDL.Null,
  });
  const Gender = IDL.Variant({ 'female' : IDL.Null, 'male' : IDL.Null });
  const WargaData = IDL.Record({
    'id' : IDL.Text,
    'dob' : IDL.Text,
    'job' : IDL.Text,
    'nik' : IDL.Text,
    'status' : StatusWarga,
    'kkNumber' : IDL.Text,
    'createdAt' : Time,
    'fullName' : IDL.Text,
    'address' : IDL.Text,
    'gender' : Gender,
    'phone' : IDL.Text,
    'maritalStatus' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Statistics = IDL.Record({
    'totalActivePengumuman' : IDL.Nat,
    'totalKK' : IDL.Nat,
    'totalWaitingSurat' : IDL.Nat,
    'totalPaidIuranThisMonth' : IDL.Nat,
    'totalWarga' : IDL.Nat,
  });
  const WebsiteSettings = IDL.Record({
    'mission' : IDL.Text,
    'name' : IDL.Text,
    'headPhone' : IDL.Text,
    'description' : IDL.Text,
    'history' : IDL.Text,
    'email' : IDL.Text,
    'fullAddress' : IDL.Text,
    'vision' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFasilitas' : IDL.Func([FasilitasData], [IDL.Text], []),
    'addIuran' : IDL.Func([IuranData], [IDL.Text], []),
    'addKK' : IDL.Func([KKData], [IDL.Text], []),
    'addPengumuman' : IDL.Func([PengumumanData], [IDL.Text], []),
    'addPengurus' : IDL.Func([PengurusData], [IDL.Text], []),
    'addSurat' : IDL.Func([SuratData], [IDL.Text], []),
    'addWarga' : IDL.Func([WargaData], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteFasilitas' : IDL.Func([IDL.Text], [], []),
    'deleteIuran' : IDL.Func([IDL.Text], [], []),
    'deleteKK' : IDL.Func([IDL.Text], [], []),
    'deletePengumuman' : IDL.Func([IDL.Text], [], []),
    'deletePengurus' : IDL.Func([IDL.Text], [], []),
    'deleteSurat' : IDL.Func([IDL.Text], [], []),
    'deleteWarga' : IDL.Func([IDL.Text], [], []),
    'filterIuranByMonthYear' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(IuranData)],
        ['query'],
      ),
    'filterIuranByStatus' : IDL.Func(
        [Status__2],
        [IDL.Vec(IuranData)],
        ['query'],
      ),
    'filterIuranByWarga' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IuranData)],
        ['query'],
      ),
    'filterSuratByStatus' : IDL.Func([Status], [IDL.Vec(SuratData)], ['query']),
    'filterSuratByWarga' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SuratData)],
        ['query'],
      ),
    'filterWargaByKK' : IDL.Func([IDL.Text], [IDL.Vec(WargaData)], ['query']),
    'filterWargaByStatus' : IDL.Func(
        [StatusWarga],
        [IDL.Vec(WargaData)],
        ['query'],
      ),
    'getAdminUsername' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFasilitas' : IDL.Func([IDL.Text], [IDL.Opt(FasilitasData)], ['query']),
    'getIuran' : IDL.Func([IDL.Text], [IDL.Opt(IuranData)], ['query']),
    'getKK' : IDL.Func([IDL.Text], [IDL.Opt(KKData)], ['query']),
    'getPengumuman' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PengumumanData)],
        ['query'],
      ),
    'getPengurus' : IDL.Func([IDL.Text], [IDL.Opt(PengurusData)], ['query']),
    'getStatistics' : IDL.Func([], [Statistics], ['query']),
    'getSurat' : IDL.Func([IDL.Text], [IDL.Opt(SuratData)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWarga' : IDL.Func([IDL.Text], [IDL.Opt(WargaData)], ['query']),
    'getWebsiteSettings' : IDL.Func([], [IDL.Opt(WebsiteSettings)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActivePengumuman' : IDL.Func([], [IDL.Vec(PengumumanData)], ['query']),
    'listFasilitas' : IDL.Func([], [IDL.Vec(FasilitasData)], ['query']),
    'listIuran' : IDL.Func([], [IDL.Vec(IuranData)], ['query']),
    'listKK' : IDL.Func([], [IDL.Vec(KKData)], ['query']),
    'listPengumuman' : IDL.Func([], [IDL.Vec(PengumumanData)], ['query']),
    'listPengurus' : IDL.Func([], [IDL.Vec(PengurusData)], ['query']),
    'listSurat' : IDL.Func([], [IDL.Vec(SuratData)], ['query']),
    'listWarga' : IDL.Func([], [IDL.Vec(WargaData)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setWebsiteSettings' : IDL.Func([WebsiteSettings], [], []),
    'updateFasilitas' : IDL.Func([FasilitasData], [], []),
    'updateIuran' : IDL.Func([IuranData], [], []),
    'updateKK' : IDL.Func([KKData], [], []),
    'updatePengumuman' : IDL.Func([PengumumanData], [], []),
    'updatePengurus' : IDL.Func([PengurusData], [], []),
    'updateSurat' : IDL.Func([SuratData], [], []),
    'updateWarga' : IDL.Func([WargaData], [], []),
    'verifyAdminCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };