/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'emergency' : null } |
  { 'important' : null } |
  { 'general' : null };
export type Condition = { 'good' : null } |
  { 'heavyDamage' : null } |
  { 'lightDamage' : null };
export interface FasilitasData {
  'id' : string,
  'acquisitionYear' : bigint,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'location' : string,
  'fasilitasType' : Type__2,
  'condition' : Condition,
}
export type Gender = { 'female' : null } |
  { 'male' : null };
export interface IuranData {
  'id' : string,
  'wargaId' : string,
  'status' : Status__2,
  'month' : bigint,
  'total' : bigint,
  'createdAt' : Time,
  'year' : bigint,
  'wargaName' : string,
  'iuranType' : Type__1,
  'paymentDate' : [] | [string],
}
export interface KKData {
  'id' : string,
  'members' : Array<string>,
  'head' : string,
  'createdAt' : Time,
  'address' : string,
  'number' : string,
}
export interface PengumumanData {
  'id' : string,
  'status' : Status__1,
  'title' : string,
  'content' : string,
  'date' : string,
  'createdAt' : Time,
  'author' : string,
  'category' : Category,
}
export interface PengurusData {
  'id' : string,
  'period' : string,
  'name' : string,
  'createdAt' : Time,
  'phone' : string,
  'photo' : string,
  'position' : string,
}
export interface Statistics {
  'totalActivePengumuman' : bigint,
  'totalKK' : bigint,
  'totalWaitingSurat' : bigint,
  'totalPaidIuranThisMonth' : bigint,
  'totalWarga' : bigint,
}
export type Status = { 'finished' : null } |
  { 'rejected' : null } |
  { 'processing' : null } |
  { 'waiting' : null };
export type StatusWarga = { 'kos' : null } |
  { 'tetap' : null } |
  { 'kontrak' : null };
export type Status__1 = { 'active' : null } |
  { 'archived' : null };
export type Status__2 = { 'paid' : null } |
  { 'unpaid' : null };
export interface SuratData {
  'id' : string,
  'wargaId' : string,
  'status' : Status,
  'applicant' : string,
  'completionDate' : [] | [string],
  'suratType' : Type,
  'createdAt' : Time,
  'notes' : [] | [string],
  'requestDate' : string,
  'purpose' : string,
}
export type Time = bigint;
export type Type = { 'kk' : null } |
  { 'ktp' : null } |
  { 'other' : null } |
  { 'poor' : null } |
  { 'domicile' : null };
export type Type__1 = { 'social' : null } |
  { 'cleaning' : null } |
  { 'security' : null } |
  { 'monthly' : null };
export type Type__2 = { 'other' : null } |
  { 'equipment' : null } |
  { 'building' : null } |
  { 'vehicle' : null };
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WargaData {
  'id' : string,
  'dob' : string,
  'job' : string,
  'nik' : string,
  'status' : StatusWarga,
  'kkNumber' : string,
  'createdAt' : Time,
  'fullName' : string,
  'address' : string,
  'gender' : Gender,
  'phone' : string,
  'maritalStatus' : string,
}
export interface WebsiteSettings {
  'mission' : string,
  'name' : string,
  'headPhone' : string,
  'description' : string,
  'history' : string,
  'email' : string,
  'fullAddress' : string,
  'vision' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFasilitas' : ActorMethod<[FasilitasData], string>,
  'addIuran' : ActorMethod<[IuranData], string>,
  'addKK' : ActorMethod<[KKData], string>,
  'addPengumuman' : ActorMethod<[PengumumanData], string>,
  'addPengurus' : ActorMethod<[PengurusData], string>,
  'addSurat' : ActorMethod<[SuratData], string>,
  'addWarga' : ActorMethod<[WargaData], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteFasilitas' : ActorMethod<[string], undefined>,
  'deleteIuran' : ActorMethod<[string], undefined>,
  'deleteKK' : ActorMethod<[string], undefined>,
  'deletePengumuman' : ActorMethod<[string], undefined>,
  'deletePengurus' : ActorMethod<[string], undefined>,
  'deleteSurat' : ActorMethod<[string], undefined>,
  'deleteWarga' : ActorMethod<[string], undefined>,
  'filterIuranByMonthYear' : ActorMethod<[bigint, bigint], Array<IuranData>>,
  'filterIuranByStatus' : ActorMethod<[Status__2], Array<IuranData>>,
  'filterIuranByWarga' : ActorMethod<[string], Array<IuranData>>,
  'filterSuratByStatus' : ActorMethod<[Status], Array<SuratData>>,
  'filterSuratByWarga' : ActorMethod<[string], Array<SuratData>>,
  'filterWargaByKK' : ActorMethod<[string], Array<WargaData>>,
  'filterWargaByStatus' : ActorMethod<[StatusWarga], Array<WargaData>>,
  'getAdminUsername' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFasilitas' : ActorMethod<[string], [] | [FasilitasData]>,
  'getIuran' : ActorMethod<[string], [] | [IuranData]>,
  'getKK' : ActorMethod<[string], [] | [KKData]>,
  'getPengumuman' : ActorMethod<[string], [] | [PengumumanData]>,
  'getPengurus' : ActorMethod<[string], [] | [PengurusData]>,
  'getStatistics' : ActorMethod<[], Statistics>,
  'getSurat' : ActorMethod<[string], [] | [SuratData]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWarga' : ActorMethod<[string], [] | [WargaData]>,
  'getWebsiteSettings' : ActorMethod<[], [] | [WebsiteSettings]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActivePengumuman' : ActorMethod<[], Array<PengumumanData>>,
  'listFasilitas' : ActorMethod<[], Array<FasilitasData>>,
  'listIuran' : ActorMethod<[], Array<IuranData>>,
  'listKK' : ActorMethod<[], Array<KKData>>,
  'listPengumuman' : ActorMethod<[], Array<PengumumanData>>,
  'listPengurus' : ActorMethod<[], Array<PengurusData>>,
  'listSurat' : ActorMethod<[], Array<SuratData>>,
  'listWarga' : ActorMethod<[], Array<WargaData>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminCredentials' : ActorMethod<[string, string], undefined>,
  'setWebsiteSettings' : ActorMethod<[WebsiteSettings], undefined>,
  'updateFasilitas' : ActorMethod<[FasilitasData], undefined>,
  'updateIuran' : ActorMethod<[IuranData], undefined>,
  'updateKK' : ActorMethod<[KKData], undefined>,
  'updatePengumuman' : ActorMethod<[PengumumanData], undefined>,
  'updatePengurus' : ActorMethod<[PengurusData], undefined>,
  'updateSurat' : ActorMethod<[SuratData], undefined>,
  'updateWarga' : ActorMethod<[WargaData], undefined>,
  'verifyAdminCredentials' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];