/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface KKData {
    id: string;
    members: Array<string>;
    head: string;
    createdAt: Time;
    address: string;
    number: string;
}
export type Time = bigint;
export interface Statistics {
    totalActivePengumuman: bigint;
    totalKK: bigint;
    totalWaitingSurat: bigint;
    totalPaidIuranThisMonth: bigint;
    totalWarga: bigint;
}
export interface WargaData {
    id: string;
    dob: string;
    job: string;
    nik: string;
    status: StatusWarga;
    kkNumber: string;
    createdAt: Time;
    fullName: string;
    address: string;
    gender: Gender;
    phone: string;
    maritalStatus: string;
}
export interface IuranData {
    id: string;
    wargaId: string;
    status: Status__2;
    month: bigint;
    total: bigint;
    createdAt: Time;
    year: bigint;
    wargaName: string;
    iuranType: Type__1;
    paymentDate?: string;
}
export interface SuratData {
    id: string;
    wargaId: string;
    status: Status;
    applicant: string;
    completionDate?: string;
    suratType: Type;
    createdAt: Time;
    notes?: string;
    requestDate: string;
    purpose: string;
}
export interface PengurusData {
    id: string;
    period: string;
    name: string;
    createdAt: Time;
    phone: string;
    photo: string;
    position: string;
}
export interface FasilitasData {
    id: string;
    acquisitionYear: bigint;
    name: string;
    createdAt: Time;
    description: string;
    location: string;
    fasilitasType: Type__2;
    condition: Condition;
}
export interface PengumumanData {
    id: string;
    status: Status__1;
    title: string;
    content: string;
    date: string;
    createdAt: Time;
    author: string;
    category: Category;
}
export interface UserProfile {
    name: string;
    role: string;
}
export interface WebsiteSettings {
    mission: string;
    name: string;
    headPhone: string;
    description: string;
    history: string;
    email: string;
    fullAddress: string;
    vision: string;
}
export enum Category {
    emergency = "emergency",
    important = "important",
    general = "general"
}
export enum Condition {
    good = "good",
    heavyDamage = "heavyDamage",
    lightDamage = "lightDamage"
}
export enum Gender {
    female = "female",
    male = "male"
}
export enum Status {
    finished = "finished",
    rejected = "rejected",
    processing = "processing",
    waiting = "waiting"
}
export enum StatusWarga {
    kos = "kos",
    tetap = "tetap",
    kontrak = "kontrak"
}
export enum Status__1 {
    active = "active",
    archived = "archived"
}
export enum Status__2 {
    paid = "paid",
    unpaid = "unpaid"
}
export enum Type {
    kk = "kk",
    ktp = "ktp",
    other = "other",
    poor = "poor",
    domicile = "domicile"
}
export enum Type__1 {
    social = "social",
    cleaning = "cleaning",
    security = "security",
    monthly = "monthly"
}
export enum Type__2 {
    other = "other",
    equipment = "equipment",
    building = "building",
    vehicle = "vehicle"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addFasilitas(fasilitasData: FasilitasData): Promise<string>;
    addIuran(iuranData: IuranData): Promise<string>;
    addKK(kkData: KKData): Promise<string>;
    addPengumuman(pengumumanData: PengumumanData): Promise<string>;
    addPengurus(pengurusData: PengurusData): Promise<string>;
    addSurat(suratData: SuratData): Promise<string>;
    addWarga(wargaData: WargaData): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteFasilitas(id: string): Promise<void>;
    deleteIuran(id: string): Promise<void>;
    deleteKK(id: string): Promise<void>;
    deletePengumuman(id: string): Promise<void>;
    deletePengurus(id: string): Promise<void>;
    deleteSurat(id: string): Promise<void>;
    deleteWarga(id: string): Promise<void>;
    filterIuranByMonthYear(month: bigint, year: bigint): Promise<Array<IuranData>>;
    filterIuranByStatus(status: Status__2): Promise<Array<IuranData>>;
    filterIuranByWarga(wargaId: string): Promise<Array<IuranData>>;
    filterSuratByStatus(status: Status): Promise<Array<SuratData>>;
    filterSuratByWarga(wargaId: string): Promise<Array<SuratData>>;
    filterWargaByKK(kkNumber: string): Promise<Array<WargaData>>;
    filterWargaByStatus(status: StatusWarga): Promise<Array<WargaData>>;
    getAdminUsername(): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFasilitas(id: string): Promise<FasilitasData | null>;
    getIuran(id: string): Promise<IuranData | null>;
    getKK(id: string): Promise<KKData | null>;
    getPengumuman(id: string): Promise<PengumumanData | null>;
    getPengurus(id: string): Promise<PengurusData | null>;
    getStatistics(): Promise<Statistics>;
    getSurat(id: string): Promise<SuratData | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWarga(id: string): Promise<WargaData | null>;
    getWebsiteSettings(): Promise<WebsiteSettings | null>;
    isCallerAdmin(): Promise<boolean>;
    listActivePengumuman(): Promise<Array<PengumumanData>>;
    listFasilitas(): Promise<Array<FasilitasData>>;
    listIuran(): Promise<Array<IuranData>>;
    listKK(): Promise<Array<KKData>>;
    listPengumuman(): Promise<Array<PengumumanData>>;
    listPengurus(): Promise<Array<PengurusData>>;
    listSurat(): Promise<Array<SuratData>>;
    listWarga(): Promise<Array<WargaData>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setAdminCredentials(username: string, passwordHash: string, currentPasswordHash: string): Promise<boolean>;
    setWebsiteSettings(settings: WebsiteSettings): Promise<void>;
    updateFasilitas(updatedFasilitas: FasilitasData): Promise<void>;
    updateIuran(updatedIuran: IuranData): Promise<void>;
    updateKK(updatedKK: KKData): Promise<void>;
    updatePengumuman(updatedPengumuman: PengumumanData): Promise<void>;
    updatePengurus(updatedPengurus: PengurusData): Promise<void>;
    updateSurat(updatedSurat: SuratData): Promise<void>;
    updateWarga(updatedWarga: WargaData): Promise<void>;
    verifyAdminCredentials(username: string, passwordHash: string): Promise<boolean>;
}
import type { Category as _Category, Condition as _Condition, FasilitasData as _FasilitasData, Gender as _Gender, IuranData as _IuranData, KKData as _KKData, PengumumanData as _PengumumanData, PengurusData as _PengurusData, Status as _Status, StatusWarga as _StatusWarga, Status__1 as _Status__1, Status__2 as _Status__2, SuratData as _SuratData, Time as _Time, Type as _Type, Type__1 as _Type__1, Type__2 as _Type__2, UserProfile as _UserProfile, UserRole as _UserRole, WargaData as _WargaData, WebsiteSettings as _WebsiteSettings } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addFasilitas(arg0: FasilitasData): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addFasilitas(to_candid_FasilitasData_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFasilitas(to_candid_FasilitasData_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addIuran(arg0: IuranData): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addIuran(to_candid_IuranData_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIuran(to_candid_IuranData_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addKK(arg0: KKData): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addKK(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addKK(arg0);
            return result;
        }
    }
    async addPengumuman(arg0: PengumumanData): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addPengumuman(to_candid_PengumumanData_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPengumuman(to_candid_PengumumanData_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPengurus(arg0: PengurusData): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addPengurus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPengurus(arg0);
            return result;
        }
    }
    async addSurat(arg0: SuratData): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addSurat(to_candid_SuratData_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSurat(to_candid_SuratData_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addWarga(arg0: WargaData): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addWarga(to_candid_WargaData_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWarga(to_candid_WargaData_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteFasilitas(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFasilitas(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFasilitas(arg0);
            return result;
        }
    }
    async deleteIuran(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteIuran(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteIuran(arg0);
            return result;
        }
    }
    async deleteKK(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteKK(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteKK(arg0);
            return result;
        }
    }
    async deletePengumuman(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePengumuman(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePengumuman(arg0);
            return result;
        }
    }
    async deletePengurus(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePengurus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePengurus(arg0);
            return result;
        }
    }
    async deleteSurat(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSurat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSurat(arg0);
            return result;
        }
    }
    async deleteWarga(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWarga(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWarga(arg0);
            return result;
        }
    }
    async filterIuranByMonthYear(arg0: bigint, arg1: bigint): Promise<Array<IuranData>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterIuranByMonthYear(arg0, arg1);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterIuranByMonthYear(arg0, arg1);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterIuranByStatus(arg0: Status__2): Promise<Array<IuranData>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterIuranByStatus(to_candid_Status__2_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterIuranByStatus(to_candid_Status__2_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterIuranByWarga(arg0: string): Promise<Array<IuranData>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterIuranByWarga(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterIuranByWarga(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterSuratByStatus(arg0: Status): Promise<Array<SuratData>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterSuratByStatus(to_candid_Status_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterSuratByStatus(to_candid_Status_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterSuratByWarga(arg0: string): Promise<Array<SuratData>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterSuratByWarga(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterSuratByWarga(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterWargaByKK(arg0: string): Promise<Array<WargaData>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterWargaByKK(arg0);
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterWargaByKK(arg0);
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterWargaByStatus(arg0: StatusWarga): Promise<Array<WargaData>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterWargaByStatus(to_candid_StatusWarga_n27(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterWargaByStatus(to_candid_StatusWarga_n27(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminUsername(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminUsername();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminUsername();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFasilitas(arg0: string): Promise<FasilitasData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFasilitas(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFasilitas(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIuran(arg0: string): Promise<IuranData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIuran(arg0);
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIuran(arg0);
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKK(arg0: string): Promise<KKData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKK(arg0);
                return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKK(arg0);
            return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPengumuman(arg0: string): Promise<PengumumanData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPengumuman(arg0);
                return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPengumuman(arg0);
            return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPengurus(arg0: string): Promise<PengurusData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPengurus(arg0);
                return from_candid_opt_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPengurus(arg0);
            return from_candid_opt_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStatistics(): Promise<Statistics> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatistics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatistics();
            return result;
        }
    }
    async getSurat(arg0: string): Promise<SuratData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSurat(arg0);
                return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSurat(arg0);
            return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWarga(arg0: string): Promise<WargaData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWarga(arg0);
                return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWarga(arg0);
            return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWebsiteSettings(): Promise<WebsiteSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWebsiteSettings();
                return from_candid_opt_n77(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWebsiteSettings();
            return from_candid_opt_n77(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listActivePengumuman(): Promise<Array<PengumumanData>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActivePengumuman();
                return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActivePengumuman();
            return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFasilitas(): Promise<Array<FasilitasData>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFasilitas();
                return from_candid_vec_n79(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFasilitas();
            return from_candid_vec_n79(this._uploadFile, this._downloadFile, result);
        }
    }
    async listIuran(): Promise<Array<IuranData>> {
        if (this.processError) {
            try {
                const result = await this.actor.listIuran();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listIuran();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listKK(): Promise<Array<KKData>> {
        if (this.processError) {
            try {
                const result = await this.actor.listKK();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listKK();
            return result;
        }
    }
    async listPengumuman(): Promise<Array<PengumumanData>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPengumuman();
                return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPengumuman();
            return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPengurus(): Promise<Array<PengurusData>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPengurus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPengurus();
            return result;
        }
    }
    async listSurat(): Promise<Array<SuratData>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSurat();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSurat();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async listWarga(): Promise<Array<WargaData>> {
        if (this.processError) {
            try {
                const result = await this.actor.listWarga();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listWarga();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setAdminCredentials(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminCredentials(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminCredentials(arg0, arg1, arg2);
            return result;
        }
    }
    async setWebsiteSettings(arg0: WebsiteSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setWebsiteSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setWebsiteSettings(arg0);
            return result;
        }
    }
    async updateFasilitas(arg0: FasilitasData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFasilitas(to_candid_FasilitasData_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFasilitas(to_candid_FasilitasData_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateIuran(arg0: IuranData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIuran(to_candid_IuranData_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIuran(to_candid_IuranData_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateKK(arg0: KKData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateKK(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateKK(arg0);
            return result;
        }
    }
    async updatePengumuman(arg0: PengumumanData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePengumuman(to_candid_PengumumanData_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePengumuman(to_candid_PengumumanData_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePengurus(arg0: PengurusData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePengurus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePengurus(arg0);
            return result;
        }
    }
    async updateSurat(arg0: SuratData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSurat(to_candid_SuratData_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSurat(to_candid_SuratData_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateWarga(arg0: WargaData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWarga(to_candid_WargaData_n25(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWarga(to_candid_WargaData_n25(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyAdminCredentials(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminCredentials(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Category_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n73(_uploadFile, _downloadFile, value);
}
function from_candid_Condition_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Condition): Condition {
    return from_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function from_candid_FasilitasData_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FasilitasData): FasilitasData {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_Gender_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_IuranData_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IuranData): IuranData {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_PengumumanData_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PengumumanData): PengumumanData {
    return from_candid_record_n69(_uploadFile, _downloadFile, value);
}
function from_candid_StatusWarga_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatusWarga): StatusWarga {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_Status__1_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status__1): Status__1 {
    return from_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function from_candid_Status__2_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status__2): Status__2 {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_SuratData_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SuratData): SuratData {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Type__1_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__1): Type__1 {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Type__2_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__2): Type__2 {
    return from_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function from_candid_Type_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type): Type {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_WargaData_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WargaData): WargaData {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FasilitasData]): FasilitasData | null {
    return value.length === 0 ? null : from_candid_FasilitasData_n59(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IuranData]): IuranData | null {
    return value.length === 0 ? null : from_candid_IuranData_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_KKData]): KKData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PengumumanData]): PengumumanData | null {
    return value.length === 0 ? null : from_candid_PengumumanData_n68(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PengurusData]): PengurusData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SuratData]): SuratData | null {
    return value.length === 0 ? null : from_candid_SuratData_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WargaData]): WargaData | null {
    return value.length === 0 ? null : from_candid_WargaData_n49(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WebsiteSettings]): WebsiteSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    wargaId: string;
    status: _Status__2;
    month: bigint;
    total: bigint;
    createdAt: _Time;
    year: bigint;
    wargaName: string;
    iuranType: _Type__1;
    paymentDate: [] | [string];
}): {
    id: string;
    wargaId: string;
    status: Status__2;
    month: bigint;
    total: bigint;
    createdAt: Time;
    year: bigint;
    wargaName: string;
    iuranType: Type__1;
    paymentDate?: string;
} {
    return {
        id: value.id,
        wargaId: value.wargaId,
        status: from_candid_Status__2_n36(_uploadFile, _downloadFile, value.status),
        month: value.month,
        total: value.total,
        createdAt: value.createdAt,
        year: value.year,
        wargaName: value.wargaName,
        iuranType: from_candid_Type__1_n38(_uploadFile, _downloadFile, value.iuranType),
        paymentDate: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.paymentDate))
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    wargaId: string;
    status: _Status;
    applicant: string;
    completionDate: [] | [string];
    suratType: _Type;
    createdAt: _Time;
    notes: [] | [string];
    requestDate: string;
    purpose: string;
}): {
    id: string;
    wargaId: string;
    status: Status;
    applicant: string;
    completionDate?: string;
    suratType: Type;
    createdAt: Time;
    notes?: string;
    requestDate: string;
    purpose: string;
} {
    return {
        id: value.id,
        wargaId: value.wargaId,
        status: from_candid_Status_n44(_uploadFile, _downloadFile, value.status),
        applicant: value.applicant,
        completionDate: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.completionDate)),
        suratType: from_candid_Type_n46(_uploadFile, _downloadFile, value.suratType),
        createdAt: value.createdAt,
        notes: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.notes)),
        requestDate: value.requestDate,
        purpose: value.purpose
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    dob: string;
    job: string;
    nik: string;
    status: _StatusWarga;
    kkNumber: string;
    createdAt: _Time;
    fullName: string;
    address: string;
    gender: _Gender;
    phone: string;
    maritalStatus: string;
}): {
    id: string;
    dob: string;
    job: string;
    nik: string;
    status: StatusWarga;
    kkNumber: string;
    createdAt: Time;
    fullName: string;
    address: string;
    gender: Gender;
    phone: string;
    maritalStatus: string;
} {
    return {
        id: value.id,
        dob: value.dob,
        job: value.job,
        nik: value.nik,
        status: from_candid_StatusWarga_n51(_uploadFile, _downloadFile, value.status),
        kkNumber: value.kkNumber,
        createdAt: value.createdAt,
        fullName: value.fullName,
        address: value.address,
        gender: from_candid_Gender_n53(_uploadFile, _downloadFile, value.gender),
        phone: value.phone,
        maritalStatus: value.maritalStatus
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    acquisitionYear: bigint;
    name: string;
    createdAt: _Time;
    description: string;
    location: string;
    fasilitasType: _Type__2;
    condition: _Condition;
}): {
    id: string;
    acquisitionYear: bigint;
    name: string;
    createdAt: Time;
    description: string;
    location: string;
    fasilitasType: Type__2;
    condition: Condition;
} {
    return {
        id: value.id,
        acquisitionYear: value.acquisitionYear,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        location: value.location,
        fasilitasType: from_candid_Type__2_n61(_uploadFile, _downloadFile, value.fasilitasType),
        condition: from_candid_Condition_n63(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status__1;
    title: string;
    content: string;
    date: string;
    createdAt: _Time;
    author: string;
    category: _Category;
}): {
    id: string;
    status: Status__1;
    title: string;
    content: string;
    date: string;
    createdAt: Time;
    author: string;
    category: Category;
} {
    return {
        id: value.id,
        status: from_candid_Status__1_n70(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        date: value.date,
        createdAt: value.createdAt,
        author: value.author,
        category: from_candid_Category_n72(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    unpaid: null;
}): Status__2 {
    return "paid" in value ? Status__2.paid : "unpaid" in value ? Status__2.unpaid : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    social: null;
} | {
    cleaning: null;
} | {
    security: null;
} | {
    monthly: null;
}): Type__1 {
    return "social" in value ? Type__1.social : "cleaning" in value ? Type__1.cleaning : "security" in value ? Type__1.security : "monthly" in value ? Type__1.monthly : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    finished: null;
} | {
    rejected: null;
} | {
    processing: null;
} | {
    waiting: null;
}): Status {
    return "finished" in value ? Status.finished : "rejected" in value ? Status.rejected : "processing" in value ? Status.processing : "waiting" in value ? Status.waiting : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kk: null;
} | {
    ktp: null;
} | {
    other: null;
} | {
    poor: null;
} | {
    domicile: null;
}): Type {
    return "kk" in value ? Type.kk : "ktp" in value ? Type.ktp : "other" in value ? Type.other : "poor" in value ? Type.poor : "domicile" in value ? Type.domicile : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kos: null;
} | {
    tetap: null;
} | {
    kontrak: null;
}): StatusWarga {
    return "kos" in value ? StatusWarga.kos : "tetap" in value ? StatusWarga.tetap : "kontrak" in value ? StatusWarga.kontrak : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
}): Gender {
    return "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    equipment: null;
} | {
    building: null;
} | {
    vehicle: null;
}): Type__2 {
    return "other" in value ? Type__2.other : "equipment" in value ? Type__2.equipment : "building" in value ? Type__2.building : "vehicle" in value ? Type__2.vehicle : value;
}
function from_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    good: null;
} | {
    heavyDamage: null;
} | {
    lightDamage: null;
}): Condition {
    return "good" in value ? Condition.good : "heavyDamage" in value ? Condition.heavyDamage : "lightDamage" in value ? Condition.lightDamage : value;
}
function from_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    archived: null;
}): Status__1 {
    return "active" in value ? Status__1.active : "archived" in value ? Status__1.archived : value;
}
function from_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emergency: null;
} | {
    important: null;
} | {
    general: null;
}): Category {
    return "emergency" in value ? Category.emergency : "important" in value ? Category.important : "general" in value ? Category.general : value;
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IuranData>): Array<IuranData> {
    return value.map((x)=>from_candid_IuranData_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SuratData>): Array<SuratData> {
    return value.map((x)=>from_candid_SuratData_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WargaData>): Array<WargaData> {
    return value.map((x)=>from_candid_WargaData_n49(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PengumumanData>): Array<PengumumanData> {
    return value.map((x)=>from_candid_PengumumanData_n68(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FasilitasData>): Array<FasilitasData> {
    return value.map((x)=>from_candid_FasilitasData_n59(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Condition_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Condition): _Condition {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_FasilitasData_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FasilitasData): _FasilitasData {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Gender_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_IuranData_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IuranData): _IuranData {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_PengumumanData_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PengumumanData): _PengumumanData {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_StatusWarga_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StatusWarga): _StatusWarga {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_Status__1_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): _Status__1 {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Status__2_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__2): _Status__2 {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_SuratData_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SuratData): _SuratData {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Type__1_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__1): _Type__1 {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Type__2_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__2): _Type__2 {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Type_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): _Type {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_WargaData_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WargaData): _WargaData {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Status__1;
    title: string;
    content: string;
    date: string;
    createdAt: Time;
    author: string;
    category: Category;
}): {
    id: string;
    status: _Status__1;
    title: string;
    content: string;
    date: string;
    createdAt: _Time;
    author: string;
    category: _Category;
} {
    return {
        id: value.id,
        status: to_candid_Status__1_n15(_uploadFile, _downloadFile, value.status),
        title: value.title,
        content: value.content,
        date: value.date,
        createdAt: value.createdAt,
        author: value.author,
        category: to_candid_Category_n17(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    acquisitionYear: bigint;
    name: string;
    createdAt: Time;
    description: string;
    location: string;
    fasilitasType: Type__2;
    condition: Condition;
}): {
    id: string;
    acquisitionYear: bigint;
    name: string;
    createdAt: _Time;
    description: string;
    location: string;
    fasilitasType: _Type__2;
    condition: _Condition;
} {
    return {
        id: value.id,
        acquisitionYear: value.acquisitionYear,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        location: value.location,
        fasilitasType: to_candid_Type__2_n3(_uploadFile, _downloadFile, value.fasilitasType),
        condition: to_candid_Condition_n5(_uploadFile, _downloadFile, value.condition)
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    wargaId: string;
    status: Status;
    applicant: string;
    completionDate?: string;
    suratType: Type;
    createdAt: Time;
    notes?: string;
    requestDate: string;
    purpose: string;
}): {
    id: string;
    wargaId: string;
    status: _Status;
    applicant: string;
    completionDate: [] | [string];
    suratType: _Type;
    createdAt: _Time;
    notes: [] | [string];
    requestDate: string;
    purpose: string;
} {
    return {
        id: value.id,
        wargaId: value.wargaId,
        status: to_candid_Status_n21(_uploadFile, _downloadFile, value.status),
        applicant: value.applicant,
        completionDate: value.completionDate ? candid_some(value.completionDate) : candid_none(),
        suratType: to_candid_Type_n23(_uploadFile, _downloadFile, value.suratType),
        createdAt: value.createdAt,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        requestDate: value.requestDate,
        purpose: value.purpose
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    dob: string;
    job: string;
    nik: string;
    status: StatusWarga;
    kkNumber: string;
    createdAt: Time;
    fullName: string;
    address: string;
    gender: Gender;
    phone: string;
    maritalStatus: string;
}): {
    id: string;
    dob: string;
    job: string;
    nik: string;
    status: _StatusWarga;
    kkNumber: string;
    createdAt: _Time;
    fullName: string;
    address: string;
    gender: _Gender;
    phone: string;
    maritalStatus: string;
} {
    return {
        id: value.id,
        dob: value.dob,
        job: value.job,
        nik: value.nik,
        status: to_candid_StatusWarga_n27(_uploadFile, _downloadFile, value.status),
        kkNumber: value.kkNumber,
        createdAt: value.createdAt,
        fullName: value.fullName,
        address: value.address,
        gender: to_candid_Gender_n29(_uploadFile, _downloadFile, value.gender),
        phone: value.phone,
        maritalStatus: value.maritalStatus
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    wargaId: string;
    status: Status__2;
    month: bigint;
    total: bigint;
    createdAt: Time;
    year: bigint;
    wargaName: string;
    iuranType: Type__1;
    paymentDate?: string;
}): {
    id: string;
    wargaId: string;
    status: _Status__2;
    month: bigint;
    total: bigint;
    createdAt: _Time;
    year: bigint;
    wargaName: string;
    iuranType: _Type__1;
    paymentDate: [] | [string];
} {
    return {
        id: value.id,
        wargaId: value.wargaId,
        status: to_candid_Status__2_n9(_uploadFile, _downloadFile, value.status),
        month: value.month,
        total: value.total,
        createdAt: value.createdAt,
        year: value.year,
        wargaName: value.wargaName,
        iuranType: to_candid_Type__1_n11(_uploadFile, _downloadFile, value.iuranType),
        paymentDate: value.paymentDate ? candid_some(value.paymentDate) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__2): {
    paid: null;
} | {
    unpaid: null;
} {
    return value == Status__2.paid ? {
        paid: null
    } : value == Status__2.unpaid ? {
        unpaid: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__1): {
    social: null;
} | {
    cleaning: null;
} | {
    security: null;
} | {
    monthly: null;
} {
    return value == Type__1.social ? {
        social: null
    } : value == Type__1.cleaning ? {
        cleaning: null
    } : value == Type__1.security ? {
        security: null
    } : value == Type__1.monthly ? {
        monthly: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): {
    active: null;
} | {
    archived: null;
} {
    return value == Status__1.active ? {
        active: null
    } : value == Status__1.archived ? {
        archived: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    emergency: null;
} | {
    important: null;
} | {
    general: null;
} {
    return value == Category.emergency ? {
        emergency: null
    } : value == Category.important ? {
        important: null
    } : value == Category.general ? {
        general: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    finished: null;
} | {
    rejected: null;
} | {
    processing: null;
} | {
    waiting: null;
} {
    return value == Status.finished ? {
        finished: null
    } : value == Status.rejected ? {
        rejected: null
    } : value == Status.processing ? {
        processing: null
    } : value == Status.waiting ? {
        waiting: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): {
    kk: null;
} | {
    ktp: null;
} | {
    other: null;
} | {
    poor: null;
} | {
    domicile: null;
} {
    return value == Type.kk ? {
        kk: null
    } : value == Type.ktp ? {
        ktp: null
    } : value == Type.other ? {
        other: null
    } : value == Type.poor ? {
        poor: null
    } : value == Type.domicile ? {
        domicile: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StatusWarga): {
    kos: null;
} | {
    tetap: null;
} | {
    kontrak: null;
} {
    return value == StatusWarga.kos ? {
        kos: null
    } : value == StatusWarga.tetap ? {
        tetap: null
    } : value == StatusWarga.kontrak ? {
        kontrak: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    female: null;
} | {
    male: null;
} {
    return value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type__2): {
    other: null;
} | {
    equipment: null;
} | {
    building: null;
} | {
    vehicle: null;
} {
    return value == Type__2.other ? {
        other: null
    } : value == Type__2.equipment ? {
        equipment: null
    } : value == Type__2.building ? {
        building: null
    } : value == Type__2.vehicle ? {
        vehicle: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Condition): {
    good: null;
} | {
    heavyDamage: null;
} | {
    lightDamage: null;
} {
    return value == Condition.good ? {
        good: null
    } : value == Condition.heavyDamage ? {
        heavyDamage: null
    } : value == Condition.lightDamage ? {
        lightDamage: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
